#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  8 12:31:34 2019

@author: shreevathsa
"""

cubes = []
for value in range(1,11):
    cube = value**3
    cubes.append(cube)
    
print(cubes)